version: "3.5"
services:
  database:
    image: amsterdam/postgres11
    environment:
      POSTGRES_DB: iiif_auth_proxy
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev

  x-app: &base-app
    build:
      context: .
      target: app
    depends_on:
      - database
    volumes:
      - ./src:/src
      - ./tests:/tests
      - ./deploy:/deploy
    ports:
      - "8000:8000"
    environment: &base-app-env
      SECRET_KEY: 'insecure'
      START_STUNNEL: 'false'
      IIIF_IMAGE_SERVER_WABO_CERT: dGhlIGNvbnRlbnRzIG9mIHRoZSBjZXJ0IGZpbGU=  # This says "the contents of the cert file"

  dev:
    <<: *base-app
    build:
      context: .
      target: dev
    command: python manage.py runserver 0.0.0.0:8000

  app:
    <<: *base-app
    build:
      context: .
      target: app
    image: docker-registry.data.amsterdam.nl/datapunt/iiif-auth-proxy:${VERSION:-latest}
    command: /deploy/docker-run.sh

  test:
    <<: *base-app
    build:
      context: .
      target: tests
    environment:
      <<: *base-app-env
      DJANGO_SETTINGS_MODULE: "main.settings"
